### ISSUE TITLE
Dev is dead

### ISSUE THREAD

**Issue by AEsirson** [nullism/clickingbad#147]
I suspect an atm crushed his head.

**Comment by SlipSlot** [comment]
If he wasn't then...

**Comment by nullism** [comment]
Hi all, I'm not dead! I've been working on other projects. Clicking Bad was a fun experiment, and I'm constantly shocked by the support I've received. Thank you all very much. I don't know that there's much more for me to do with CB, and I encourage forks. There's a fairly popular fork on IOS called Tapping Bad, and I believe that dev has since added features. 

Thanks again!
